services:
  frontend:
    container_name: students_testing_system_frontend
    build: ./ui
    ports:
      - "3000:3000"
    networks:
      - frontend-network

  backend:
    container_name: students_testing_system_backend
    build: ./service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/students_testing_system_db
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - frontend-network
      - backend-network

  db:
    container_name: students_testing_system_db
    image: postgres:11
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: students_testing_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

volumes:
  db-data:

networks:
  frontend-network:
  backend-network:
